### ISSUE TITLE
Structure Issue / Mild Insanity

### ISSUE THREAD

**Issue by Ulysses256** [TeamWizardry/Wizardry#68] opened 2017-12-08 20:20 UTC
Hello there Team Wizardry!

My issue is with the mana battery's structure. While the crafting altar froms fine, I just can't seem to form the other. I tried with mana pearls in the holder, or without them, excavating the structure so it's in air, rebuilding it multiple times, applying warm pig fat to the wood so it doesn't creak, but I'm running out of ideas here. If I'm stupid, or did something wrong, please do tell. 

Technical Data:
- Minecraft Version: 1.12.2
- Forge Mod Loader version: 14.23.1.2555
- Modpack: All The Mods 3 v5.3
- Mod version: wizardry-0.6.0

Album of shame: https://imgur.com/a/3F0mU

**Comment by Demoniaque** [comment] 2017-12-08 21:41
Apparently a known issue.

**Comment by Demoniaque** [comment] 2017-12-10 21:45
Please check if the issue is resolved in the latest version. Structure errors are highlighted.

**Comment by Demoniaque** [comment] 2017-12-10 22:05
This is one edge case that's staying unresolved.

**Comment by Demoniaque** [comment] 2017-12-11 18:12
GUESS WHAT. This has been solved. Will be in the next update.

**Closed** 2017-12-11 18:12 UTC
