### ISSUE TITLE
texture issue with spellbook

### ISSUE THREAD

**Issue by MortalGoddess** [TeamWizardry/Wizardry#222] opened 2018-12-10 00:50 UTC
In version 0.9.7, with forge version 14.23.5.2775, I am having a texture issue where the majority of the spell forger codex is unreadable, causing any progression in the mod impossible. 
See image for more details. 
There are other mods, and a detailed list can be provided if you believe that is the issue, however I ran this collection of mods before with minor difference and no issue. What  the new mods are is a much shorter list, that can also be provided/marked for testing purposes
![mc issue](https://user-images.githubusercontent.com/43297317/49705233-2fa48e80-fbeb-11e8-9a31-3b426c9b9604.PNG)
(Edit for typo)

**Comment by Demoniaque** [comment] 2018-12-10 14:08
Do you have betterFPS installed? if so, try any other algorithm in the menus

**Comment by MortalGoddess** [comment] 2018-12-10 14:35
That would be the problem, I will let you know what algorithm I am using so that a note can be placed on the mod page and/or you can work with the betterFPS people to see about another potential fix

**Comment by Demoniaque** [comment] 2018-12-10 14:41
This issue should already be resolved in the latest librarianlib jar

**Comment by MortalGoddess** [comment] 2018-12-10 21:50
I have the latest version of librarianlib, version 4.15 for 1.12.2 
using Riven's half-algorithm for testing purposes.

**Comment by MortalGoddess** [comment] 2018-12-10 22:39
I have removed BetterFPS and it's still an issue

**Comment by MortalGoddess** [comment] 2018-12-11 18:16
new mods for testing with

Modular powersuit - 0.6.0.20
Forgelin - 1.8.2
shotguns and glitter -1.5 (same issue exists with this book)
runs of wizardry - 0.9.1
subcommonlib - 1.2.0.4
rpginventory - 5.3.0.0
GiacomosFishinNet - 1.6.1
autoreglib - 1.3-21
bullseye - 3.0.6
tammodized - 0.15.6
Angel of Vengeance - 0.9.3
extra botany - r1.1-48
  Botania was in before version r1.10-357
Monk Mod - 1.4
DimensionalDoors - 3.0.9-287
enchantment descriptions -1.1.13
abyssalcraft integration -1.6.6
  Abyssalcraft was also in before the issue version 1.9.4.14

If you have any ideas on what might narrow this down let me know.

**Comment by Demoniaque** [comment] 2018-12-29 12:17
The issue is angel of Vengeance and we dont know why yet

**Closed by Demoniaque** 2018-12-29 12:17 UTC
