### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ralseilii** [TeamWizardry/Wizardry#352] opened 2024-01-14 06:46 UTC
the latest version will crash whenever you have options.txt and open magic crafter to click one Magic.when delete options.txt it willnot crash, but Minecraft always generates options.txt.

and it will crash when you have fluidapi and right click mana battery

**Comment by Hadaward** [comment] 2024-01-14 07:49
Thanks about your feedback, i will work to fix this issue. Can you send me some additional attachments to verify this issue? Preferably in the crash_reports folder send me the most recent log. Additionally, it would be interesting if you could comment step by step on the problem, so I can confirm that the problem is indeed with the mod and not an incompatibility.

**Comment by ralseilii** [comment] 2024-01-14 09:41
here is my option.txt: https://mclo.gs/KyLfJpG and crash report:https://mclo.gs/KFSiDS3

**Comment by ralseilii** [comment] 2024-01-14 09:47
and here is crash report with Fluidlogged-API-:
https://mclo.gs/UNTKCn8

 Besides,Whenever I open the Spellforger Codex, the font becomes non-Unicode. I have to click once in the language settings to change it back, but when I reopen the book, it reverts again.
![2024-01-14_17 44 16](https://github.com/TeamWizardry/Wizardry/assets/112687747/9813bc5e-1069-49a5-a729-09f81dccce36)
![2024-01-14_17 44 24](https://github.com/TeamWizardry/Wizardry/assets/112687747/9f16fcbd-9721-418b-a036-13ea0edaf3a1)
![2024-01-14_17 44 27](https://github.com/TeamWizardry/Wizardry/assets/112687747/b8b44a52-681b-4acb-bf2b-5583f615e1b9)

**Comment by Hadaward** [comment] 2024-01-14 10:28
Can you reproduce this crash, if so could you give me a step by step guide? I couldn't reproduce it. You can also try disabling the textures you have active, some of them may be conflicting with the mods and texts containing unicodes that you reported in the last comment. Another question, were you playing on an online server or LAN? If so, how many players were present? Does the crash occur with just you on the server or was there someone else nearby?

**Comment by ralseilii** [comment] 2024-01-14 11:48
no im not in server and this happens on client.You can copy the following content: https://mclo.gs/IrdqmbJ to option.txt(delete all original texts in options.txt), then open the magician's worktable in the game and click on any pattern.
(wizardry-0.11.2 will cause crash,but wizardry-0.11.1 will not cause crash)

when you have fluidapi mod, right click mana battery will cause crash,this happens in both wizardry-0.11.2 and wizardry-0.11.1

**Comment by Hadaward** [comment] 2024-01-14 22:44
Can you test this build and check if the crashes continue to occur? I was not able to reproduce your issue even with your config file. I think something is changing your settings in a way that conflicts with the new wizardry sound category.

https://github.com/Hadaward/Wizardry/releases/download/v0.11.3/wizardry-0.11.3.jar

**Comment by ralseilii** [comment] 2024-01-15 07:14
still crash

**Comment by ralseilii** [comment] 2024-01-15 10:23
sorry i gave the wrong option.txt, and this is the options.txt that makes it crash when click pattern of magician's worktable :https://mclo.gs/zuaXzPc ,and it still crashes even with wizardry-0.11.3 or 0.11.2, not 0.11.1

**Comment by ralseilii** [comment] 2024-01-15 10:23
sorry i gave the wrong options.txt, this is the one that crashes when you click on any pattern ofmagician's worktable  :https://mclo.gs/2sJ6r2V , and it still crashes even with 0.11.3

**Comment by ralseilii** [comment] 2024-01-15 10:58
> Can you test this build and check if the crashes continue to occur? I was not able to reproduce your issue even with your config file. I think something is changing your settings in a way that conflicts with the new wizardry sound category.
> 
> https://github.com/Hadaward/Wizardry/releases/download/v0.11.3/wizardry-0.11.3.jar

**Comment by Hadaward** [comment] 2024-01-15 16:27
Hmm so you have more mods. I think I already know the problem, I'll correct it later.

**Comment by Hadaward** [comment] 2024-01-15 17:33
The reason for the crash is because the Dynamic Surroundings mod was overwriting the game's sound category register, I fixed this by changing where the wizardry category is registered. Test this jar to see if it won't crash again. PS: About the fluid api I would recommend to create a new issue containing all the information about it, how to reproduce the problem, the log files, which mods are present.

This should be fixed, if not you may comment again here, download the file below and test.
https://github.com/Hadaward/Wizardry/releases/download/v0.11.3/wizardry-0.11.3.jar

**Closed as completed by Hadaward** 2024-01-15 17:33 UTC

**Comment by ralseilii** [comment] 2024-01-15 19:38
yes thank you it is fixed

**Comment by ralseilii** [comment] 2024-01-16 14:57
but click on Music and Sound will cause crash

**Comment by Hadaward** [comment] 2024-01-16 14:59
Can you elaborate further? I need details to reproduce. Including which mods are present as there may be an incompatibility between them.

**Comment by FelixWoess** [comment] 2024-02-09 13:59
Yeah, my Game also crashes when clicking the Sound Settings in the Game (i used version 0.11.2 but am gonna go back to 0.11.1).
And since the crash report and log were very unclear it took me 5h to find out that this mod got an update that killed the Modpack lol.
[latest.log](https://github.com/TeamWizardry/Wizardry/files/14222572/latest.log)

I don't know if that helps + i read the mod is discontinued, but yeah im going now.

**Comment by Hadaward** [comment] 2024-02-09 18:06
There is a 0.11.3 fixing this issue, i will ask the mod authors to publish it whenever i'm home
