### ISSUE TITLE
Null cape owner

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#25] opened 2017-06-24 20:12 UTC
http://i.imgur.com/THbNaTC.png

**Comment by LordSaad44** [comment] 2017-06-26 07:57
@Sourpowerpete can you reproduce this?

**Comment by LordSaad44** [comment] 2017-07-05 10:12
Closing this because i might have possibly changed nbt or something and stuff happened. So unless this happens again, I'm closing this.

**Closed by LordSaad44** 2017-07-05 10:12 UTC
